[package]
name = "maa-runner"
authors = ["Loong Wang <wangl-cc@outlook.com>"]
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "maa-run"
path = "src/main.rs"

[dependencies]
maa-sys = { path = "../maa-sys" }
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
directories = "5"
serde_json = "1"
anyhow = "1"
toml = "0.7"
paste = "1"

[dependencies.chrono]
version = "0.4.26"
default-features = false
features = ["std", "clock", "serde"]

[build-dependencies]
directories = "5"
