name: Setup Rust
description: 'Setup Rust for cross-compilation'
inputs:
  os:
    description: 'Host and target OS'
    required: true
  arch:
    description: 'Target architecture'
    required: true
  coverage:
    description: 'Whether to install cargo-tarpaulin'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Compute Target Triple
      shell: bash
      run: |
        os=${{ inputs.os }}
        arch=${{ inputs.arch }}
        case "$os" in
          ubuntu*)
            target="$arch-unknown-linux-gnu"
            ;;
          macos*)
            target="$arch-apple-darwin"
            ;;
          windows*)
            target="$arch-pc-windows-msvc"
            ;;
          *)
            echo "Unknown OS: $os"
            exit 1
            ;;
        esac
        echo "CARGO_BUILD_TARGET=$target" >> $GITHUB_ENV
    - name: Install Target
      if: inputs.arch == 'aarch64'
      shell: bash
      run: rustup target add $CARGO_BUILD_TARGET
    - name: Cross Compile Dependencies (Linux x86_64 to Linux aarch64)
      if: inputs.arch == 'aarch64' && startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          libc6-dev-arm64-cross
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CFLAGS_aarch64_unknown_linux_gnu=--sysroot=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
    - name: Install Cargo tarpaulin
      if: fromJson(inputs.coverage)
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin
