tasks:
  - type: StartUp
    params:
      start_game_enabled:
        default: true
        description: start the game
      client_type:
        alternatives: [Official, YoStarEN, YoStarJP]
        description: a client type
        deps:
          start_game_enabled: true
  - type: Fight
    name: Fight Daily
    strategy: merge
    variants:
      - condition:
          type: Weekday
          weekdays:
            - Sun
        params:
          expiring_medicine: 5
      - params:
          stage:
            default: 1-7
            description: a stage to fight
      - condition:
          type: Weekday
          weekdays: [Tue, Thu, Sat]
          client: Official
        params:
          stage: CE-6
      - condition:
          type: DateTime
          start: 2023-08-01T16:00:00
          end: 2023-08-21T03:59:59
        params:
          stage:
            alternatives: [SL-6, SL-7, SL-8]
            default_index: 2
            description: a stage to fight in summer event
            allow_custom: true
  - type: Mall
    params:
      shopping: true
      credit_fight: true
      buy_first:
        - 招聘许可
        - 龙门币
      blacklist:
        - 碳
        - 家具
        - 加急许可
    variants:
      - condition:
          type: Time
          start: 16:00:00
  - type: CloseDown
# yaml-language-server: $schema=../../schemas/task.schema.json
