# startup game
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

[[tasks]]
type = "Fight"

# fight the last stage if on event period
[[tasks.variants]]
condition = { type = "DateTime", start = "2023-08-01T16:00:00", end = "2023-08-21T03:59:59" }
[tasks.variants.params.stage]
alternatives = ["SL-6", "SL-7", "SL-8"]
description = "a stage to fight in summer event"

# fight CE-6 on Tue, Thu, Sat
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue", "Thu", "Sat"] }
params = { stage = "CE-6" }

# fight 1-7 otherwise
[[tasks.variants]]
[tasks.variants.params.stage]
default = "1-7"
description = "a stage to fight"

# Mall after 16:00
[[tasks]]
type = "Mall"

[[tasks.variants]]
condition = { type = "Time", start = "16:00:00" }

# close game
[[tasks]]
type = "CloseDown"
