name: Install MaaCore and resource
description: Install MaaCore and resource by prebuilt CLI
inputs:
  target:
    description: Target triple used for downloading prebuilt CLI
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install Prebuilt CLI
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        target='${{ inputs.target }}'
        if [[ -z "$target" ]]; then
          target=$(rustc -vV | sed -n 's|host: ||p')
        fi

        # get the latest stable release information
        aria2c https://github.com/MaaAssistantArknights/maa-cli/raw/version/stable.json
        tag=$(jq -r .details.tag stable.json)
        name=$(jq -r ".details.assets.\"$target\".name" stable.json)
        checksum=$(jq -r ".details.assets.\"$target\".sha256sum" stable.json)

        echo "Download maa-cli $tag for $target"
        aria2c "https://github.com/MaaAssistantArknights/maa-cli/releases/download/$tag/$name"

        # use openssl to verify the checksum because it's cross-platform and available on all runners
        echo "Verify the checksum of $name with $checksum"
        dgst=$(openssl dgst -sha256 "$name")
        file_checksum=${dgst#*= }
        if [[ $file_checksum != "$checksum" ]]; then
          echo "Checksum mismatch: $file_checksum"
          exit 1
        fi

        echo "Extracting $name"
        case "$name" in
          *.tar.gz)
            tar -xzvf "$name"
            ;;
          *.zip)
            unzip "$name"
            ;;
        esac
        mv -v maa_cli-$target/maa* .
    - name: Install MaaCore and resource
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        MAA=MaaAssistantArknights
        ./maa install beta -t0 -vv \
          --api-url "https://github.com/$MAA/MaaRelease/raw/main/$MAA/api/"
        core_dir=$(./maa dir lib)
        resource_dir=$(./maa dir resource)
        version=$(./maa version core)
        version=${version#MaaCore v}
        ls -l "$core_dir"
        ls -l "$resource_dir"
        {
          echo "MAA_CORE_DIR=$core_dir"
          echo "MAA_RESOURCE_DIR=$resource_dir"
          echo "MAA_CORE_VERSION=v$version"
        } >> "$GITHUB_ENV"
    - name: Cleanup
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        ./maa cleanup --batch
        rm -vrf maa_cli* stable.json maa*
