[[tasks]]
type = "StartUp"

[tasks.params]
client_type = "Official"
start_game_enabled = true

[[tasks]]
name = "剿灭"
type = "Fight"

[tasks.params]
series = 0
stage = "Annihilation"

[[tasks]]
name = "理智作战"
type = "Fight"

[tasks.params]
medicine_expire_days = 2
series = 0

[[tasks.variants]]

[tasks.variants.condition]
type = "OnSideStory"

[tasks.variants.params]
series = 0
stage = "TO-5"

[[tasks.variants]]

[tasks.variants.condition]
timezone = "Official"
type = "Weekday"
weekdays = [
    "Tue",
    "Thu",
    "Sat",
    "Sun",
]

[tasks.variants.params]
series = 0
stage = "CE-6"

[[tasks.variants]]

[tasks.variants.condition]
type = "Always"

[tasks.variants.params]
series = 0
stage = "LS-6"

[[tasks]]
type = "Recruit"

[tasks.params]
confirm = [
    5,
    4,
    3,
]
extra_tags_mode = 0
refresh = true
select = [
    5,
    4,
    3,
]
times = 4

[tasks.params.recruitment_time]
3 = 540
4 = 540

[[tasks]]
type = "Infrast"

[tasks.params]
continue_training = true
dorm_notstationed_enabled = true
dorm_trust_enabled = true
facility = [
    "Mfg",
    "Trade",
    "Control",
    "Power",
    "Reception",
    "Office",
    "Dorm",
    "Processing",
    "Training",
]
filename = "/Users/nan/一图流-153-一天两换-MAA.json"
mode = 10000
reception_clue_exchange = true
reception_message_board = true
reception_send_clue = true
replenish = true
threshold = 0.3

[[tasks.variants]]

[tasks.variants.condition]
end = "21:00:00"
start = "09:00:00"
type = "Time"

[tasks.variants.params]
plan_index = 0

[[tasks.variants]]

[tasks.variants.condition]
end = "09:00:00"
start = "21:00:00"
type = "Time"

[tasks.variants.params]
plan_index = 1

[[tasks]]
type = "Mall"

[tasks.params]
blacklist = [
    "碳",
    "家具",
]
buy_first = [
    "加急许可",
    "招聘许可",
]
credit_fight = false
force_shopping_if_credit_full = true
formation_index = 0
only_buy_discount = false
reserve_max_credit = false
shopping = true
visit_friends = true

[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true
mining = true
orundum = true
recruit = false
specialaccess = true

[[tasks]]
type = "Roguelike"

[tasks.params]
core_char = "维什戴尔"
enable = false
investment_enabled = true
investment_with_more_score = false
investments_count = 999
mode = 1
only_start_with_elite_two = false
refresh_trader_with_dice = false
roles = "稳扎稳打"
squad = "指挥分队"
start_with_elite_two = false
starts_count = 999999
stop_at_final_boss = false
stop_at_max_level = false
stop_when_investment_full = true
theme = "JieGarden"
use_nonfriend_support = false
use_support = false

[[tasks]]
type = "Reclamation"

[tasks.params]
enable = false
increment_mode = 0
mode = 1
num_craft_batches = 16
theme = "Tales"
